spring:
  datasource:
    url: jdbc:postgresql://recommendation-db:5432/recommendation
    username: postgres
    password: "0000"
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
    generate-ddl: true
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      # Chat 모델 설정
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.3
      
      # Embedding 모델 설정
      embedding:
        options:
          model: text-embedding-3-small
          dimensions: 768

services:
  restaurant:
    url: http://host.docker.internal:8080
kakao:
  rest-api-key: ${KAKAO_REST_API_KEY}