spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/restaurant_db
    username: postgres
    password: "0000"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  ai:
    vertex:
      ai:
        credentials-uri: classpath:vertex_ai_key.json
        gemini:
          project-id: ace-metric-465309-n8
          location: us-central1
          chat:
            enabled: true
            options:
              model: gemini-2.0-flash
        embedding:
          project-id: ace-metric-465309-n8
          location: us-central1
          text:
            enabled: true
            options:
              model: text-embedding-004
              task-type: RETRIEVAL_DOCUMENT
